### PR TITLE
Add version check that checks github for latest release

### PR DESCRIPTION
**Pull request by supernothing**

### CODE REVIEW

**Comment by mrtizmoatwork** [comment]
@supernothing @Rizato while you are making these changes, can you also revise the directory structure and the use of __init__.py in the same way as we are revising all of the engines?

**Comment by supernothing** [comment]
@mrtizmoatwork If these are now requirements for projects, we should be tracking these code standards somewhere, letting people know about them, and tracking the progress of porting code to these standards in an epic.

**Comment by supernothing** [comment]
As for the requested changes:

1. This should be as it is, `src/polyswarm_api`, not `polyswarm_api`. The reason for this is one may want to add more modules. A bunch of top level folders can make it unclear what is code and what is not.
4. We use `find_packages` in a number of other projects; this allows us to add modules without updating the `setup.py` script. It seems like needless work to me to manually enumerate them.
5. This also seems backwards to me. Why not create a separate `test_requirements.txt` and use that as well for testing requirements? There's no reason to do more mixing code and data here.
6. `package_dir` is defined, it's just used by `find_packages` to build a list of modules dynamically.

**Comment by Rizato** [comment]
The changes are more inline with the typical approach to python libraries and modules for distribution.

**Comment by Rizato** [comment]
For example https://github.com/aio-libs/aioredis

**Comment by supernothing** [comment]
Are these standards somewhere? `pip` best practices? There's a lot of variation in these things by project from everything I can tell, so I'm not sure pointing out particular ones makes sense. For instance, `urllib3`, the most downloaded package after `pip`, uses a `src/urllib3` dir. `pip`, likewise, uses a `src` dir. 

I'd rather just consider these changes on the merits of which creates more work for us in the future, and it seems to me that these are net-neutral or net-negative when it comes to that.

**Comment by mrtizmoatwork** [comment]
I'm perfectly ok with your points 2,3,4 remaining as you originally coded them.
For point 1, yeah it's probably a "preference thing". I don't see a "you must do this". But, what I will say is that our "polyswarm-api" project will only have things that relate to polyswarm-api, so the root directory being named "polyswarm_api" is normal. And then if we later brake code into sub modules that need their own directories, they would go inside of (as subdirs) "polyswarm_api". They would not go at the project root. What this page describes as "Installable Single Package" or "Application with Internal Packages" is what I'm thinking of: https://realpython.com/python-application-layouts/.

**Comment by Rizato** [comment]
https://hynek.me/articles/testing-packaging/
In the case for a `src` dir.

**Comment by supernothing** [comment]
I'm not describing sub-modules of `polyswarm_api`, which of course are just sub-directories of `polyswarm_api`.

Sometimes you want to have multiple top-level modules in the same application that will be installed (this is a pretty common thing to do, see spider, apikeymgmt, and artifact-index). So then we would start littering the root directory with some_other_module names, and it becomes unclear what is code and what is not, in addition to needing to add new modules to `setup.py` every time.

This is definitely a *preference* thing, as there's not standards I'm aware of, but my experience has been it reduces amount of edits you have to do to `setup.py` when you change things, and it makes the top level directory cleaner to use a `src` dir.

**Comment by mrtizmoatwork** [comment]
Good argument. I'm cool with using the `src` dir for source code. For engines though, I don't think it matters since they are quite simple and we are not expanding them to be anything else.

**Pull request merged**
